---
- hosts: localhost
  connection: local
  vars:
    zerotier_cli_pkg: "{{ 'zerotier-cli' if ansible_os_family == 'Darwin' else 'zerotier-one' }}"
    additional_pkgs:
      - neofetch
      - mtr
      - nmap
      - bpython
      - zsh
      - terraform
      - git
      - python3
  tasks:
    - name: Update package manager.
      package:
        update_cache: yes

    # - name: Install Zerotier-CLI
    #   package:
    #     name: "{{ zerotier_cli_pkg }}"
    #     state: present

    # - name: Join Zerotier network
    #   shell: zerotier-cli join {{ network_id }}
    #   register: join_output
    #   ignore_errors: true

    # - name: Debug output
    #   debug:
    #     var: join_output
    #   when: join_output.stdout is defined

    - name: Install additional packages
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ additional_pkgs }}"

    - name: Install Oh My Zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when: ansible_os_family == "Darwin" or ansible_os_family == "Debian"

    # - name: Add Zerotier-CLI to system startup
    #   copy:
    #     src: zerotier-cli
  handlers:
    - name: Reload systemctl daemon
      systemd:
        daemon_reload: yes
