---
- hosts: localhost
  connection: local
  vars:
    zerotier_cli_pkg: "{{ 'zerotier-cli' if ansible_os_family == 'Darwin' else 'zerotier-one' }}"
    additional_pkgs:
      - neofetch
      - mtr
      - nmap
      - bpython
      - zsh
      # - terraform
      - git
      - python3
  tasks:
    - name: Update package manager.
      package:
        update_cache: yes

    - name: Install Zerotier
      script: curl -s https://install.zerotier.com/ | sudo bash

    - name: Join Zerotier network
      block:
        - shell: zerotier-cli join {{ network_id }}
          register: join_output
          ignore_errors: true
      rescue:
        - debug:
            msg: "Install Zerotier-CLI failed"
      dependencies:
        - Install Zerotier

    - name: Debug output
      debug:
        var: join_output
      when: join_output.stdout is defined

    - name: Enable and start Zerotier service
      service:
        name: zerotier-one
        state: started
        enabled: yes

    - name: Download Terraform binary
      unarchive:
        src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
      vars:
        terraform_version: 0.15.5

    - name: Set executable permission on Terraform binary
      file:
        path: /usr/local/bin/terraform
        mode: 0755

    - name: Install additional packages # All other packages.
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ additional_pkgs }}"

    - name: Install Oh My Zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when: ansible_os_family == "Darwin" or ansible_os_family == "Debian"


  handlers:
    - name: Reload systemctl daemon
      systemd:
        daemon_reload: yes



